[project]
name = "tp4-secuguard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Raffaele FARVACQUE", email = "raffaele.farvacque@student.junia.com" }
]
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
]

[project.scripts]
tp4-secuguard = "tp4_secuguard:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
