[project]
name = "tp4-securguard"
version = "0.1.0"
description = "Boîte à outils CLI de sécurité des mots de passe"
readme = "README.md"
authors = [
    { name = "Raffaele FARVACQUE", email = "raffaele.farvacque@student.junia.com" }
]
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
]

[project.scripts]
secuguard = "secuguard.main:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "secuguard"
module-root = "src"